import { DefaultTheme, DarkTheme } from "@react-navigation/native";

export const Colors = {
    light: {
        ...DefaultTheme.colors,
        primary: "#0045f5",
        primaryLight: "#3368f7",
        primaryDark: "#0031ad",
        background: "#f0f3fb",
        backgroundLight: "#ffffff",
        backgroundDark: "#d8dbe3",
        card: "#e3e8fb",
        cardLight: "#ffffff",
        cardDark: "#d8dbe3",
        text: "#0a101e",
        textLight: "#3a3f4d",
        textDark: "#000000",
        border: "#d3d3d3",
        borderLight: "#e0e0e0",
        borderDark: "#a8a8a8",
        notification: "#ff7261",
        notificationLight: "#ff8e80",
        notificationDark: "#cc5b4d",
        secondary: "#8ca5e5",
        secondaryLight: "#a8bceb",
        secondaryDark: "#7084b7",
        accent: "#567ddf",
        accentLight: "#7897e5",
        accentDark: "#3a5a9b",
        error: "#ff7261",
        errorLight: "#ff8e80",
        errorDark: "#cc5b4d",
        success: "#13c886",
        successLight: "#42d39e",
        successDark: "#0e9f6a",
        white: "#e0e7f5",
        warning: "#ffc107", // Added warning color
    },
    dark: {
        ...DarkTheme.colors,
        primary: "#0a50ff",
        primaryLight: "#0738b3",
        primaryDark: "#3b73ff",
        background: "#040710",
        backgroundLight: "#000000",
        backgroundDark: "#1a1d26",
        card: "#081023",
        cardLight: "#000000",
        cardDark: "#2a2a2a",
        text: "#e0e7f5",
        textLight: "#a8b1c2",
        textDark: "#f0f3fb",
        border: "#2d2d2d",
        borderLight: "#1a1a1a",
        borderDark: "#4a4a4a",
        notification: "#ff7261",
        notificationLight: "#cc5b4d",
        notificationDark: "#ff8e80",
        secondary: "#1a3474",
        secondaryLight: "#122356",
        secondaryDark: "#2a4a94",
        accent: "#2046a7",
        accentLight: "#16327b",
        accentDark: "#3b66c7",
        error: "#ff7261",
        errorLight: "#cc5b4d",
        errorDark: "#ff8e80",
        success: "#13c886",
        successLight: "#0e9f6a",
        successDark: "#42d39e",
        white: "#e0e7f5",
        warning: "#ffc107", // Added warning color
        warningLight: "#ffab00", // Lighter shade for contrast
        warningDark: "#ffca28", // Darker shade for contrast
    },
};
